# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0ed9d8cb2b5d85dbe4956594ac9f1c99f67a36f4086dbfc1dd8ec942f95ff25b7bdec808320de822e8ff02c079615c4ced065c5c8ebe85ad12990a171fd8308e

test:
  secret_key_base: 2041e54937680633c52cd0685ef1e5a010966799257156c75ab19ec65c3e2a44021a20decbefed9d77b53169d3468679bc6269282dbdbda661fc936d2f14ccd3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
